WHAT IS PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

A replacement for NumPy to use the power of GPUs

a deep learning research platform that provides maximum flexibility and speed


this repository contains code from the pytorch website tutorial

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
# TENSORS
#Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

from __future__ import print_function


In [2]:
import torch

In [3]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [4]:
# Construct a 5x3 matrix, randomly initialized:

x = torch.rand(5,3)
print(x)

tensor([[0.2055, 0.2586, 0.0016],
        [0.8184, 0.1879, 0.1172],
        [0.4520, 0.7352, 0.7936],
        [0.3069, 0.9399, 0.6405],
        [0.1541, 0.5958, 0.1578]])


In [5]:
# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# Construct a tensor directly from data:

x= torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
# create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3377,  1.0844,  0.9389],
        [-1.3041, -0.9179,  0.7408],
        [ 0.2937,  0.0671, -0.6223],
        [ 1.4716, -0.4931,  0.4018],
        [-1.0953,  0.1302,  1.7026]])


In [12]:
# Get SIZE 

print(x.size())


# torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


In [13]:
# OPERATIONS

# ADDITION 1

y = torch.rand(5,3)
print(x+y)

tensor([[ 0.3964,  1.7733,  1.6962],
        [-1.1320, -0.3479,  1.6805],
        [ 1.2562,  0.6019, -0.5388],
        [ 2.0358,  0.1376,  0.6709],
        [-0.7312,  0.1310,  2.0849]])


In [14]:
# ADDITION 2

print(torch.add(x , y))

tensor([[ 0.3964,  1.7733,  1.6962],
        [-1.1320, -0.3479,  1.6805],
        [ 1.2562,  0.6019, -0.5388],
        [ 2.0358,  0.1376,  0.6709],
        [-0.7312,  0.1310,  2.0849]])


In [15]:
# Addition: providing an output tensor as argument

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3964,  1.7733,  1.6962],
        [-1.1320, -0.3479,  1.6805],
        [ 1.2562,  0.6019, -0.5388],
        [ 2.0358,  0.1376,  0.6709],
        [-0.7312,  0.1310,  2.0849]])


In [19]:
# addition in place

y.add_(x)
print(y)

tensor([[ 0.0587,  2.8577,  2.6351],
        [-2.4361, -1.2658,  2.4213],
        [ 1.5499,  0.6690, -1.1611],
        [ 3.5074, -0.3555,  1.0727],
        [-1.8265,  0.2612,  3.7874]])


In [20]:
# INDEXING

print(x[:,1])

tensor([ 1.0844, -0.9179,  0.0671, -0.4931,  0.1302])


In [21]:
# RESIZING

#Resizing: If you want to resize/reshape tensor, you can use torch.view

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size() , y.size() , z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
print(y)

tensor([ 0.5045, -0.7923, -0.8637, -0.4896, -0.8114, -0.5050, -0.0530, -1.0406,
         0.4469, -1.4793,  0.1147,  0.0289,  0.1114,  0.7485,  0.9310, -0.2725])


In [23]:
print(x)

tensor([[ 0.5045, -0.7923, -0.8637, -0.4896],
        [-0.8114, -0.5050, -0.0530, -1.0406],
        [ 0.4469, -1.4793,  0.1147,  0.0289],
        [ 0.1114,  0.7485,  0.9310, -0.2725]])


In [24]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2486])
-1.248625636100769


In [25]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()   # converting tensor to numpy array
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [28]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [29]:
print(b)

[2. 2. 2. 2. 2.]


In [30]:
# Converting NumPy Array to Torch Tensor

import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out =a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# CUDA Tensors

#Tensors can be moved onto any device using the .to method.

if torch.cuda.is_available():
    device = torch.device("cuda")  #a CUDA device object
    y = torch.ones_like(x, device = device)   #directly create tensor on GPU
    x = x.to(device)            # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))   # ``.to`` can also change dtype together!