<a href="https://colab.research.google.com/github/AashiDutt/Pytorch/blob/master/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [0]:
# from numpy import dot   for dot product

In [3]:
v = torch.tensor([1,2,3,4,5,6])
print(v)               

tensor([1, 2, 3, 4, 5, 6])


In [4]:
print(v.dtype)

torch.int64


In [5]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [0]:
f = torch.FloatTensor([10.24,9,8,7,6])

In [7]:
print(f)

tensor([10.2400,  9.0000,  8.0000,  7.0000,  6.0000])


In [8]:
print(f.size())

torch.Size([5])


In [9]:
f.view(5,1)    # shaping tensor

tensor([[10.2400],
        [ 9.0000],
        [ 8.0000],
        [ 7.0000],
        [ 6.0000]])

In [10]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)  # numpy array to tensor conversion
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [12]:
# tensor to numpy arr conversion
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]


In [0]:
# One Dimentional array    
one_d = torch.arange(0,9)
# torch.arange(starting_integer,no. of integers)

In [14]:
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
# 2D array
two_d = one_d.view(3,3)

In [16]:
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [17]:
 two_d.dim()

2

In [18]:
# getting tensor value using indexing
two_d[1,2]

tensor(5)

In [19]:
print(two_d[2,1])

tensor(7)


In [0]:
 x = torch.arange(18).view(3,2,3)
  # torch.arrange(no. of integers).view(no. of block,no. of ROWS,no. of COLUMN)

In [21]:
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [22]:
# INDEXING
x[1,1,1]   # 1st matrix (from 0, 1 and 2 matrix)
            # 1st row of 1st matrix 
            # 1st column
      

tensor(10)

In [23]:
x[2,1,2] 

tensor(17)

In [24]:
#SLICING
x[1,0:2,0:3]   
#[matrix 1,rows 0:2  means 0 and 1,column 0:3 means 0 to 2 ]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [27]:
x[2,0:2,0:3]

tensor([[12, 13, 14],
        [15, 16, 17]])

In [28]:
x[2,1:,0:3]

tensor([[15, 16, 17]])

In [29]:
x[0,1:,1:]

tensor([[4, 5]])

In [40]:
#MATRIX MULTIPLICATION
#RULE [A]*[B]
# no. of rows in mtrix A = no.of columns in matrix B

A = torch.tensor([0, 3, 5 ,5 ,5 ,2]).view(2,3)
A 

tensor([[0, 3, 5],
        [5, 5, 2]])

In [42]:
B = torch.tensor([3, 4,3,-2,4,-2]).view(3,2)
B

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [43]:
torch.matmul(A,B)   # matrix multiplication

tensor([[ 29, -16],
        [ 38,   6]])

In [45]:
A @ B     # @ used for matrix multiplication

tensor([[ 29, -16],
        [ 38,   6]])

In [49]:
# Gradient /Derivatives

# derivative of function gives slope of a curve  

x = torch.tensor(2.0, requires_grad=True)  # x is a float and we need to find the gradient (=True)
y = 9*x**4 + 2*x**3 +3*x**2 +6*x +1
y.backward()   # to compute derivative of y
x.grad      # to access the value

tensor(330.)

In [50]:
x

tensor(2., requires_grad=True)

In [62]:
# partial derivatives
x = torch.tensor(1.0, requires_grad=True)  # y is a function of x and
z = torch.tensor(2.0, requires_grad=True)  # y is also a function of z

y = x**2 +z**3
y.backward()   # to compute derivative of y
x.grad      # to access the value


tensor(2.)

In [60]:
z.grad

tensor(12.)