<a href="https://colab.research.google.com/github/AashiDutt/Pytorch/blob/master/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [12]:
v = torch.tensor([1,2,3,4,5,6])
print(v)               

tensor([1, 2, 3, 4, 5, 6])


In [13]:
print(v.dtype)

torch.int64


In [15]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [0]:
f = torch.FloatTensor([10.24,9,8,7,6])

In [20]:
print(f)

tensor([10.2400,  9.0000,  8.0000,  7.0000,  6.0000])


In [22]:
print(f.size())

torch.Size([5])


In [25]:
f.view(5,1)    # shaping tensor

tensor([[10.2400],
        [ 9.0000],
        [ 8.0000],
        [ 7.0000],
        [ 6.0000]])

In [27]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [33]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)  # numpy array to tensor conversion
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [34]:
# tensor to numpy arr conversion
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
